### ISSUE TITLE
[2주차 과제] 날씨 앱 클론코딩 - 시작 화면 및 상세보기

### ISSUE THREAD

**Issue by ena-isme** [DO-SOPT-iOS-Part/Shinjiwon-assignment#4]
## 🌟ISSUE 
> 첫 과제가 저에게 떨어졌습니다 !

<br/>

## 🌟TODO
✏️기본과제
- [ ] 시작화면에서 해당 나의 위치 뷰를 선택하면, 우측의 날씨 상세보기뷰로 Push되어 이동합니다. 
- [ ] 상세보기뷰는 수직 스크롤이 가능하고, 중간의 시간대별 날씨의 경우 수평스크롤이 가능해야 합니다. 
- [ ] 하단의 리스트 보기 버튼을 선택할 경우, 시작화면으로 POP되면 됩니다.

<br/>

✏️심화과제
- [ ] 여러개의 지역별 날씨 데이터를 추가해주세요. (최소 3개이상)
- [ ] 위의 서치바를 이용해서 특정 지역을 검색할 수 있게 해주세요.
- [ ] 실시간 검색까진 필요 없고, “의정부시” 라면 “의정부시”를 검색 했을때 해당 지역이 검색되어, 리스트에 남아있으면 됩니다. 
- [ ] 해당 리스트들의 개수 만큼 상세보기 뷰 에서 수평 스크롤로 이동이 가능하게 만들어주세요. 

! 헷갈리는 부분이 있다면, 핸드폰의 기본 날씨앱을 이용해서 판단해주세요 !
