### ISSUE TITLE
[3주차 과제] 날씨 앱 클론코딩 - 상세 뷰 추가 구현

### ISSUE THREAD

**Issue by ena-isme** [DO-SOPT-iOS-Part/Shinjiwon-assignment#6]
## 🌟ISSUE 
[3주차 과제] 날씨 앱 클론코딩 - 상세 뷰 추가 구현 

## 🌟TODO
<기본>
- [ ]  TableView, CollectionView로 재구현
- [ ] 10일간의 일기예보 뷰 추가

<심화>
- [ ] 위로 스크롤 할때 헤더가 접히며 올라가도록 구현
- [ ] 10일간의 일기예보에 있는 그라디언트 뷰 이미지를 사용하지 않고 구현
